export const PAYMENT_LIST: Record<string, number> = {
  "Above ten thousand people": 0.5,
  "Wu Dong Qian Kun": 0.5,
  "Martial peak": 0.7,
  "Ranker's Return": 0.5,
  "Trash Of The Count's Family": 0.5,
  "Worn and torn newbie": 0.5,
  "The Demonic Cult Leader is too Reluctant": 0.5,
  "The Eternal Supreme": 0.9,
  "The Board Of Lanke": 0.5,
  "The 31st Piece Turns the Tables": 0.7,
  "Clever Cleaning Life Of The Returned Genius Hunter": 0.5,
  "Transcension Academy": 0.6,
  "The Knight King Who Returned with a God": 0.5,
  "The Priest Of Corruption": 0.5,
  "The Emperor's Sword": 0.5,
  "Steel eating player": 0.5,
  "Surviving the apocalypse": 0.5,
  "Subscribing To The Transcendent's Channel": 0.7,
  "I Was Immediately Mistaken for a Monster Genius Actor": 1.5,
  "Reincarnated as a Genius Prodigy of a Prestigious Family": 0.6,
  "All my alter egos are tycoons": 0.8,
  "The Delusional Hunter in Another World": 0.8,
  "Entomologist in sichuan tang clan": 0.9,
  "The Ultimate Shut-In": 1.5,
  "Becoming a legendary ace employee": 0.7,
  "I'm Being Misunderstood As A Soccer Genius": 1.2,
  "The Game That I Came From": 0.5,
  "Lord of the Mysteries": 0.5,
  "Regressed Genius Creates Mythic Items": 0.6,
  "All Soccer Talents Are Mine": 0.5,
  "Mount Hua Sect's Genius Phantom Swordsman": 0.7,
  "Disciple of the Three Kings": 0.5,
  "Becoming a Legend, Starting as a Water Monkey": 0.5,
  "Genius Artist's Random Studio": 0.5,
  "Artifact-Devouring Player": 0.5,
  "The Villain Wants to Live": 1.0,
  "The Illegitimate Who Devours Weapons": 1.0,
  "The Magic Tower's Problem Child": 0.7,
  "I Became the Genius Bastard of a Noble Dark Clan": 0.6,
  "Winterbell": 0.5,
  "Emperor of Solo Play": 0.5,
  "My Wife is the Demonic Cult Leader": 0.5,
  "I Took Over the Academy With a Single Sashimi Knife": 1.3,
  "The Youngest Son of the Eunhae Merchant Group": 0.5,
  "The Dark Swordsman Returns": 0.8,
  "Unrivaled Spear Demon": 2.0,
  "The Top Ranker's Aspiring Writer Life Manual": 0.5,
  "A Cadet Becomes A Prophet?!": 0.6,
  "The Demonic Cult Instructor Returns": 0.5,
  "Turn-based wizard": 0.5,
  "Zombie papa": 0.5,
  "A Mountain of Corpses, A Sea of Blood": 0.5,
  "Chronicle of Runes": 0.6,
  "Hiding a warehouse in the apocalypse": 1.0,
  "Did Someone Force You to Become the Heavenly Demon?": 0.6,
  "Monopolizing Fortunes": 1.1,
  "The Rebellious Apostle of the Harvest Goddess": 0.5,
  "Return of the First Generation": 1.1,
  "Rebirth of the Divine Demon": 0.8,
  "44th Period: Survival Class": 0.5,
  "I Shall Seal The Heavens 2025": 0.8,
  "Impure Blood Regression": 0.5,
  "The Vehement Emperor Of Steel": 1.2,
  "The Regressed Extra Becomes a Genius": 0.7,
  "Reincarnated as the Archduke's Son": 1.0,
  "Solo Leveling:ARISE": 0.5,
  "Kidnapped Dragons": 1.0,
  "Eater of All": 0.9,
  "Legend of Star General": 0.4,
  "Absolute Domination at Level 0 Using My Analysis Skill": 0.8,
  "Murim Psychopath": 0.9,
  "Reincarnation of Martial God": 0.5,
  "The Prosecutor: Kim Seo-jin": 0.6,
  "The Black-Haired Knight King": 0.5,
  "The Game Architect Of The Abyss": 0.5,
  "The 18-Year-Old Demon King": 0.6,
  "The Postman of the Apocalypse": 0.5,
  "The Black-Haired U.S. Army General": 0.7,
  "Rural Ace": 0.5,
  "A Glimpse of the Jianghu": 0.5,
  "Assassin X Dragon": 0.5,
  "Return from Ailao Mountain": 0.5,
  "The Player Hides His Past": 0.5,
  "Return to Player": 0.5,
  "The Terminally Ill Young Master of the Baek Clan": 0.5,
  "How to live as a Villain": 0.5,
  "The Academy's Genius Tamer": 0.5,
  "The Hero Directed by The Demon King": 0.5,
  "Resurrection Boy": 0.5,
  "My School Life Pretending To Be a Worthless Person": 0.5,
  "Manager Kim": 0.5,
  "Light Of The Dawn (Remake)": 0.5,
  "Demonic Beast Hunter Survival Guide": 0.5,
  "The Martial World's Undead Apocalypse": 0.5,
  "Genius Prismatic Mage": 0.5,
};

export const attached_assets = PAYMENT_LIST;
